import assert from "node:assert/strict";
import { it } from "node:test";
import { deriveTasteFillQueries, encodeTasteFillCursor, decodeTasteFillCursor, shouldRunTasteFill, selectTasteFillItems, TASTE_FILL_MAX_QUERIES, TASTE_FILL_MIN_REMAINING_MS, TASTE_FILL_CURSOR_PREFIX, TASTE_FILL_TREND_SOURCE } from "./recommendationTasteFill.ts";
import type { RecommendationPreferenceProfile } from "./recommendationEngine.ts";
const profile = (types: [string, number][] = [], genres: [string, number][] = []) => ({ content_type_scores: new Map(types), genre_scores: new Map(genres) }) as RecommendationPreferenceProfile;
const preferred = profile([["kdrama",10],["anime",6],["movie",1]], [["드라마",10],["로맨스",8],["코미디",5],["액션",2]]);
const userFilters = { excludedThemeKeys: [], excludedGenres: [] };
const base = { profile: preferred, mediaType: "all" as const, userFilters };
const query = (group: string, countries: string[], genres = ["romance","comedy"]) => ({ key: `${group}:${countries.join(",")}:${genres.join("|")}`, group, kind: group === "movie" ? "movie" : "tv", countries, genres });
it("Q-1 derives the two highest taste groups and specific genres", () => assert.deepEqual(deriveTasteFillQueries(base), [query("drama-KR",["KR"]),query("anime",["JP"])]));
it("Q-2 breaks content score ties in stable group order", () => assert.deepEqual(deriveTasteFillQueries({...base,profile:profile([["jdrama",3],["kdrama",3]])}), [query("drama-KR",["KR"],[]),query("drama-JP",["JP"],[])]));
it("Q-3 uses initial-user groups without genres", () => assert.deepEqual(deriveTasteFillQueries({...base,profile:profile()}),[query("drama-KR",["KR"],[]),query("anime",["JP"],[])]));
it("Q-4 limits explicit movie discovery to the movie group", () => assert.deepEqual(deriveTasteFillQueries({...base,discoveryFilters:{mediaTypes:["movie"]}}),[query("movie",[])]));
it("Q-5 combines Japanese drama and anime with explicit romance", () => assert.deepEqual(deriveTasteFillQueries({...base,discoveryFilters:{mediaTypes:["drama","anime"],countries:["JP"],genres:["로맨스"]}}),[query("drama",["JP"],["romance"]),query("anime",["JP"],["romance"])]));
it("Q-6 excludes anime from explicit Korean discovery", () => assert.deepEqual(deriveTasteFillQueries({...base,discoveryFilters:{mediaTypes:["drama","anime"],countries:["KR"]}}),[query("drama",["KR"])]));
it("Q-7 removes excluded genres before choosing the top two", () => assert.deepEqual(deriveTasteFillQueries({...base,userFilters:{excludedThemeKeys:[],excludedGenres:["로맨스"]}}).map(q=>q.genres),[["comedy","action"],["comedy","action"]]));
it("Q-8 expands explicit drama and anime to three queries", () => assert.deepEqual(deriveTasteFillQueries({...base,discoveryFilters:{mediaTypes:["drama","anime"]}}).map(q=>q.group),["drama-KR","drama-JP","anime"]));
it("C-1 round trips a combined cursor", () => { const state={catalog:"abc",catalogDone:false,taste:{k:{page:2,done:false}}}; const encoded=encodeTasteFillCursor(state); assert.ok(encoded?.startsWith("tf1.")); assert.deepEqual(decodeTasteFillCursor(encoded),state); });
it("C-2 preserves a legacy catalog cursor", () => assert.deepEqual(decodeTasteFillCursor("legacy-cursor"),{catalog:"legacy-cursor",catalogDone:false,taste:{}}));
it("C-3 resets corrupt and invalid combined cursors", () => { for(const raw of ["tf1.!!!","tf1."+btoa('{"catalog":1}'),null]) assert.deepEqual(decodeTasteFillCursor(raw),{catalog:null,catalogDone:false,taste:{}}); });
it("C-4 ends only when catalog and all taste pages are done", () => { assert.equal(encodeTasteFillCursor({catalog:null,catalogDone:true,taste:{a:{page:3,done:true}}}),null); assert.equal(encodeTasteFillCursor({catalog:null,catalogDone:true,taste:{}}),null); assert.ok(encodeTasteFillCursor({catalog:null,catalogDone:true,taste:{a:{page:2,done:false}}})?.startsWith("tf1.")); });
it("S-1 requires a vacant slot and at least 2500ms", () => { assert.equal(shouldRunTasteFill({itemCount:4,limit:12,remainingMs:3000}),true); assert.equal(shouldRunTasteFill({itemCount:12,limit:12,remainingMs:9000}),false); assert.equal(shouldRunTasteFill({itemCount:0,limit:12,remainingMs:2499}),false); });
it("P-1 skips existing and blocked identities while filling", () => { const [a,b,c,d]=["1","2","3","4"].map(id=>({id})); assert.deepEqual(selectTasteFillItems({ranked:[a,b,c,d],existing:[b],blockedIdentities:new Set(["3"]),need:2,identities:x=>[x.id]}),[a,d]); });
it("K-1 exposes the agreed taste fill constants", () => { assert.equal(TASTE_FILL_MAX_QUERIES,3); assert.equal(TASTE_FILL_MIN_REMAINING_MS,2500); assert.equal(TASTE_FILL_CURSOR_PREFIX,"tf1."); assert.equal(TASTE_FILL_TREND_SOURCE,"취향 장르 인기작"); });
