import { useSafeAreaInsets } from "react-native-safe-area-context";
import { useModalFocus } from "@/hooks/useModalFocus";
import { ActivityIndicator, Modal, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { Ionicons } from "@expo/vector-icons";
import { GenreBadgeList } from "@/components/GenreBadge";
import { AppImage as Image } from "@/components/common/AppImage";
import { colors, radius, spacing } from "@/constants/theme";
import { useExternalContentDetail } from "@/hooks/useContentSearch";
import type { SimilarContentResult } from "@/services/similarContent";

export function SimilarContentQuickViewModal({item,addLabel,isAddDisabled,onClose,onAdd,onOpenDetails,onFindSimilar}:{item:SimilarContentResult|null;addLabel:string;isAddDisabled:boolean;onClose:()=>void;onAdd:(item:SimilarContentResult)=>void;onOpenDetails:(item:SimilarContentResult)=>void;onFindSimilar:(item:SimilarContentResult)=>void;}){
  const insets = useSafeAreaInsets();
  const { panelRef, firstRef, focusFirst } = useModalFocus(Boolean(item));
  const detail=useExternalContentDetail(item?.external_source,item?.external_id,item?.content_type==="movie"?"movie":"tv"); if(!item)return null;
  const content=detail.data?.content; const overview=content?.localized_overview||content?.overview||item.localized_overview||item.overview;
  const tags=item.shared_signals.filter((signal)=>["tag","genre"].includes(signal.type)).map((signal)=>signal.label);
  return <Modal onShow={focusFirst} animationType="fade" onRequestClose={onClose} transparent visible><View accessibilityViewIsModal style={[styles.backdrop,{paddingTop:Math.max(insets.top,16),paddingBottom:Math.max(insets.bottom,16)}]}><Pressable accessibilityLabel="빠른 보기 닫기" onPress={onClose} style={StyleSheet.absoluteFill}/><View accessibilityLabel={`${item.title_primary} 빠른 보기`} ref={panelRef} role="dialog" aria-modal accessibilityViewIsModal style={styles.dialog}><View style={styles.header}><Text numberOfLines={2} style={styles.title}>{item.title_primary}</Text><Pressable accessibilityLabel="빠른 보기 닫기" ref={firstRef} accessibilityRole="button" onPress={onClose} style={styles.close}><Ionicons color={colors.text} name="close" size={22}/></Pressable></View><ScrollView style={{flexShrink:1}} contentContainerStyle={styles.content}><View style={styles.hero}><Image contentFit="cover" source={item.poster_url?{uri:item.poster_url}:null} style={styles.poster}/><View style={styles.summary}><GenreBadgeList genres={content?.genres?.length?content.genres:item.genres} maxVisible={5}/><Text style={styles.meta}>{[item.air_year,item.episode_count?`${item.episode_count}화`:null].filter(Boolean).join(" · ")}</Text></View></View>{detail.isLoading?<ActivityIndicator color={colors.primary}/>:null}{overview?<Section title="작품 소개"><Text style={styles.text}>{overview}</Text></Section>:null}<Section title="기준 작품과 비슷한 이유"><Text style={styles.text}>{item.similarity_reason}</Text></Section>{tags.length?<Section title="공통 태그"><Text style={styles.muted}>{tags.join(" · ")}</Text></Section>:null}{item.studios?.length?<Section title="제작사 · 스튜디오"><Text style={styles.muted}>{item.studios.join(", ")}</Text></Section>:null}{item.people?.length?<Section title={item.content_type==="anime"?"주요 참여진":"주요 출연진"}><Text style={styles.muted}>{item.people.join(", ")}</Text></Section>:null}<View style={styles.footer}><Pressable accessibilityRole="button" onPress={()=>onFindSimilar(item)} style={styles.similar}><Text style={styles.similarText}>이 작품과 비슷한 작품 찾기</Text></Pressable><Pressable accessibilityRole="button" onPress={()=>onOpenDetails(item)} style={styles.secondary}><Text style={styles.secondaryText}>상세 보기</Text></Pressable><Pressable accessibilityRole="button" disabled={isAddDisabled} onPress={()=>onAdd(item)} style={[styles.primary,isAddDisabled&&styles.disabled]}><Text style={styles.primaryText}>{addLabel}</Text></Pressable></View></ScrollView></View></View></Modal>;
}
function Section({title,children}:{title:string;children:React.ReactNode}){return <View style={styles.section}><Text style={styles.sectionTitle}>{title}</Text>{children}</View>}
const styles=StyleSheet.create({backdrop:{alignItems:"center",backgroundColor:"rgba(17,24,39,.58)",flex:1,justifyContent:"center",padding:spacing.lg},dialog:{backgroundColor:colors.surface,borderRadius:radius.lg,maxHeight:"92%",maxWidth:720,overflow:"hidden",width:"100%"},header:{alignItems:"center",borderBottomColor:colors.border,borderBottomWidth:StyleSheet.hairlineWidth,flexDirection:"row",justifyContent:"space-between",padding:spacing.lg},title:{color:colors.text,flex:1,fontSize:20,fontWeight:"900"},close:{minHeight:44,minWidth:44,alignItems:"center",justifyContent:"center",padding:spacing.sm},content:{gap:spacing.lg,padding:spacing.lg},hero:{flexDirection:"row",gap:spacing.lg},poster:{borderRadius:radius.md,height:132,width:88},summary:{flex:1,gap:spacing.sm},meta:{color:colors.textMuted,fontWeight:"700"},section:{gap:spacing.xs},sectionTitle:{color:colors.text,fontSize:14,fontWeight:"900"},text:{color:colors.text,fontSize:14,lineHeight:22},muted:{color:colors.textMuted,fontSize:13,lineHeight:20},footer:{borderTopColor:colors.border,borderTopWidth:StyleSheet.hairlineWidth,flexDirection:"row",flexWrap:"wrap",gap:spacing.sm,justifyContent:"flex-end",padding:spacing.lg},similar:{minHeight:44,justifyContent:"center",borderColor:colors.primary,borderRadius:radius.md,borderWidth:1,padding:spacing.md},similarText:{color:colors.primary,fontWeight:"900"},secondary:{minHeight:44,justifyContent:"center",borderColor:colors.border,borderRadius:radius.md,borderWidth:1,padding:spacing.md},secondaryText:{color:colors.text,fontWeight:"900"},primary:{minHeight:44,justifyContent:"center",backgroundColor:colors.primary,borderRadius:radius.md,padding:spacing.md},primaryText:{color:colors.surface,fontWeight:"900"},disabled:{opacity:.55}});
